// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KcIwQ1tEASzdtamOFrRay0_-4S7JEPo',
    appId: '1:564731061695:android:8b2c76a46177fca772ed0a',
    messagingSenderId: '564731061695',
    projectId: 'clean-bloc-c1414',
    storageBucket: 'clean-bloc-c1414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZm8k5zf2mvYSt6M_JZl0qs0u-Ez3qAG4',
    appId: '1:564731061695:ios:f60b7adcfb0fcb2972ed0a',
    messagingSenderId: '564731061695',
    projectId: 'clean-bloc-c1414',
    storageBucket: 'clean-bloc-c1414.appspot.com',
    iosBundleId: 'com.example.blocCleanApp',
  );
}
